version: '2'
services:
  time-backend:
    environment:
      - ConfigPath=./config/config.yaml
    image: ${RELEASE_PREFIX}-time:${RELEASE_TAG}
    container_name: ${PROJECT_NAME}-${DEV_USER}-time-backend-test
    volumes:
      - ../release/config/.backend-config.yaml:/go/src/evolution/config/config.yaml
    command: /bin/sh -c "./time-init-db && ./time"
    expose:
      - "${TIME_PORT}"
    networks:
      - default
  system-backend:
    environment:
      - ConfigPath=./config/config.yaml
    image: ${RELEASE_PREFIX}-system:${RELEASE_TAG}
    container_name: ${PROJECT_NAME}-${DEV_USER}-system-backend-test
    volumes:
      - ../release/config/.backend-config.yaml:/go/src/evolution/config/config.yaml
    command: /bin/sh -c "./system-init-db && ./system"
    expose:
      - "${SYSTEM_PORT}"
    networks:
      - default
  frontend:
    image: ${RELEASE_PREFIX}-frontend:${RELEASE_TAG}
    container_name: ${PROJECT_NAME}-${DEV_USER}-system-frontend-test
    volumes:
      - ../../frontend/src/assets/config/.config.prod.json:/www/assets/config/.config.prod.json
      - ../../frontend/src/assets/config/.config.prod.json:/www/assets/config/config.prod.json
    ports:
      - "${FRONT_PORT}:80" 
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
