version: '2'
services:
  grafana:
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=a1b2c3d4e
    image: grafana/grafana:4.6.2-1000
    container_name: ${COMPOSE_PROJECT_NAME}-${DEV_USER}-grafana
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      # - /etc/passwd:/etc/passwd
      - ./grafana:/var/lib/grafana
    # user: "${DEV_UID}:${DEV_UID}"
    ports:
      - "3000:3000"
  influxdb:
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    image: influxdb:1.4.2
    container_name: ${COMPOSE_PROJECT_NAME}-${DEV_USER}-influxdb
    volumes:
      - /home/wuzhongyang/database/influxdb:/var/lib/influxdb
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "8083:8083"
networks:
  default:
    external:
      name: ${DEV_USER}
