app:
  mode: debug
  log: /go/src/evolution/logs
  level: 2
quant:
  system:
    name: quant
    host: 
    port: 8080 
    version: v1 
    prefix: evolution/quant
    cors: [""]
    location: Asia/Shanghai
  redis:
    host: redis
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: 
    port: 
    user: 
    target:  
    password: 
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    location: Asia/Shanghai
  rpc:
    host: 
    port: 
time:
  system:
    name: time
    host: 
    port: 8080 
    version: v1 
    prefix: evolution/time
    cors: [""]
    location: Asia/Shanghai
  redis:
    host: redis
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: 
    port: 
    user: 
    target: 
    password: 
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    location: Asia/Shanghai
system:
  auth:
    type: "BAJwt"
    session: "auth-session"
  system:
    name: system 
    host: 
    port: 8080 
    version: v1 
    prefix: evolution/system
    cors: [""]
    location: Asia/Shanghai
  redis:
    host: redis
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: 
    port: 
    user: 
    target:  
    password: 
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    location: Asia/Shanghai
