app:
  mode: release 
  log: /go/src/evolution/logs
  level: 3
quant:
  system:
    name: quant
    host: http://evolution-quant
    port: 8080
    version: v1 
    prefix: quant
    cors: ["http://fireseed.cn:30888"]
    location: Asia/Shanghai
  redis:
    host: redis 
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: mysql 
    port: 3306
    user: root
    target: quant
    password: 
    maxIdle: 10 
    maxOpen: 5 
    showsql: False
    reset: False
    location: Asia/Shanghai
  rpc:
    host: evolution-engine
    port: 6666
time:
  system:
    name: time
    host: http://evolution-time
    port: 8080 
    version: v1 
    prefix: time
    cors: ["http://fireseed.cn:30888"]
    location: Asia/Shanghai
  redis:
    host: redis 
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: mysql 
    port: 3306
    user: root
    target: time
    password: 
    maxIdle: 10 
    maxOpen: 5 
    showsql: False 
    reset: False 
    location: Asia/Shanghai
system:
  auth:
    type: "BAJwt"
    session: "auth-session"
  system:
    name: system 
    host: http://evolution-system
    port: 8080 
    version: v1 
    prefix: system
    cors: ["http://fireseed.cn:30888"]
    location: Asia/Shanghai
  redis:
    host: redis 
    port: 6379
    password: 
    db: 0
  database:
    type: mysql
    host: mysql 
    port: 3306
    user: root
    target: system 
    password: 
    maxIdle: 10 
    maxOpen: 5 
    showsql: False
    reset: False
    location: Asia/Shanghai
