static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: evolution 
            virtual_hosts:
            - name: evolution 
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/quant"
                route:
                  cluster: quant 
              - match:
                  prefix: "/time"
                route:
                  cluster: time 
              - match:
                  prefix: "/system"
                route:
                  cluster: system 
              - match:
                  prefix: "/"
                route:
                  cluster: frontend 
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: quant
    connect_timeout: 0.5s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: evolution-quant
        port_value: 8080
  - name: time 
    connect_timeout: 0.5s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: evolution-time
        port_value: 8080
  - name: system
    connect_timeout: 0.5s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: evolution-system
        port_value: 8080
  - name: frontend 
    connect_timeout: 0.5s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: evolution-frontend 
        port_value: 80 
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
