kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: evolution-quant
  name: evolution-quant
  namespace: default 
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    k8s-app: evolution-quant
