kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: evolution-quant
  name: evolution-quant
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: evolution-quant
  template:
    metadata:
      labels:
        k8s-app: evolution-quant
    spec:
      containers:
      - name: quant 
        image: stoneagle/evolution-quant:v0.0.1-alpha1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /go/src/evolution/config
      volumes:
      - name: config-volume
        configMap:
          name: evolution-backend-config
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
